# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bungie_sdk/all/bungie_sdk.rbi
#
# bungie_sdk-0.1.0

module BungieSdk
end
class BungieSdk::Error < StandardError
end
